FROM ghcr.io/astral-sh/uv:python3.12-trixie

RUN adduser agentbeats
USER agentbeats
RUN mkdir -p /home/agentbeats/.cache/uv
WORKDIR /home/agentbeats/tutorial

COPY pyproject.toml uv.lock README.md ./
COPY src src

RUN \
    --mount=type=cache,target=/home/agentbeats/.cache/uv,uid=1000 \
    uv sync --locked

COPY scenarios scenarios

ENTRYPOINT ["uv", "run", "scenarios/tau2/tau2_agent.py"]
CMD ["--host", "0.0.0.0"]
EXPOSE 9019
