[green_agent]
endpoint = "http://127.0.0.1:9009"
cmd = "python scenarios/GAIA/assistant_evaluator.py --host 127.0.0.1 --port 9009"

[[participants]]
role = "assistant"
endpoint = "http://127.0.0.1:9019"
cmd = "python scenarios/GAIA/assistant.py --host 127.0.0.1 --port 9019"

[config]
run_gaia = true
evaluation_level = "all"
gaia_split = "validation"

run_docvqa = false
docvqa_num_samples = 100
docvqa_seed = 0

run_sealqa = false
sealqa_subset = "seal_0"
